name: Setup Node.js
description: Setup Node.js

inputs:
  node-version:
    required: false
    description: "Node.js version"
    default: "20"
  pnpm-version:
    required: false
    description: "pnpm version"
    default: "10.6.3"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        version: ${{ inputs.pnpm-version }}
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Get cache path
      id: cache
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4.2.2
      with:
        path: ${{ steps.cache.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.package-manager.outputs.name }}-
