name: Setup Node.js
description: Setup Node.js

inputs:
  node-version:
    required: false
    description: "Node.js version"
    default: ""
  pnpm-version:
    required: false
    description: "pnpm version"
    default: "10.18.1"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false
        version: ${{ inputs.pnpm-version }}
    - name: Detect node version
      id: detect-node-version
      shell: bash
      run: |
        if [ -z "${{ inputs.node-version }}" ]; then
          if [ -f .node-version ]; then
            echo "node_version_file=.node-version" >> $GITHUB_OUTPUT
          elif [ -f .nvmrc ]; then
            echo "node_version_file=.nvmrc" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
            echo "node_version_file=" >> $GITHUB_OUTPUT
          fi
        else
          echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
          echo "node_version_file=" >> $GITHUB_OUTPUT
        fi
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.detect-node-version.outputs.version }}
        node-version-file: ${{ steps.detect-node-version.outputs.node_version_file }}
    - name: Get cache path
      id: cache
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4.3.0
      with:
        path: ${{ steps.cache.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.package-manager.outputs.name }}-
