name: Setup Node.js
description: Setup Node.js

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  pnpm-version:
    description: "pnpm version"
    required: false
    default: "9.11.0"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        version: ${{ inputs.pnpm-version }}
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
