name: update-pr-comment

on:
  pull_request:


jobs:
  update-pr-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Update PR commit message
        uses: ./update-pr-comment
